spring:
    application:
        name: Ball don't lie
    datasource:
        url: jdbc:postgresql://localhost:5432/ball_dont_lie
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    web:
        cors:
            allowed-origins=*
            allowed-methods=GET,POST,PUT,DELETE,OPTIONS
            allowed-headers=*

jwt:
    secret: ballDontLieSecretKey
    expiration: 60

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: swagger-ui.html
